// Generated by the Blazor I18n Text compiler
namespace TapToTweetReserved.Client.I18nText
{
    public partial class Localized : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About this app"</summary>
        public string AboutThisApp;

        /// <summary>"Add"</summary>
        public string Add;

        /// <summary>"This application is designed for tweeting during a presentation by speaker oneself."</summary>
        public string ApplicationSummary;

        /// <summary>"Sign in with Twitter."</summary>
        public string ApplicationSummary_Step1;

        /// <summary>"Reserve messages."</summary>
        public string ApplicationSummary_Step2;

        /// <summary>"Tap to tweet the message that was reserved &lt;strong&gt;during your presentation!&lt;/strong&gt;"</summary>
        public string ApplicationSummary_Step3;

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"Close"</summary>
        public string Close;

        /// <summary>"Delete selected tweets.<br/>Are you sure?"</summary>
        public string Confirm_DeleteTweets;

        /// <summary>"The message text has changed.<br/>Are you sure you want to discard this change?"</summary>
        public string Confirm_DiscardChanges;

        /// <summary>"Delete"</summary>
        public string Delete;

        /// <summary>"Down"</summary>
        public string Down;

        /// <summary>"Edit"</summary>
        public string Edit;

        /// <summary>"EDIT MODE"</summary>
        public string EditMode;

        /// <summary>"EDIT MODE - Add"</summary>
        public string EditMode_Add;

        /// <summary>"EDIT MODE - Edit"</summary>
        public string EditMode_Edit;

        /// <summary>"Home"</summary>
        public string GoToHome;

        /// <summary>"Edit Mode..."</summary>
        public string GotToEdit;

        /// <summary>"Click &quot;Add&quot; to reserve a new message to tweet after."</summary>
        public string Guide_in_Edit;

        /// <summary>"Open menu and click &quot;Edit...&quot; to reserve messages to tweet after."</summary>
        public string Guide_in_Home;

        /// <summary>"No"</summary>
        public string No;

        /// <summary>"OK"</summary>
        public string OK;

        /// <summary>"About..."</summary>
        public string OpenAboutBox;

        /// <summary>"Reload"</summary>
        public string Reload;

        /// <summary>"Sign In with Twitter"</summary>
        public string SignIn;

        /// <summary>"Sign Out"</summary>
        public string SignOut;

        /// <summary>"Oops, something wrong..."</summary>
        public string Tweet_Step0_Error;

        /// <summary>"Tweet after 3sec...."</summary>
        public string Tweet_Step1_Before3Sec;

        /// <summary>"Tweet after 2sec..."</summary>
        public string Tweet_Step2_Before2Sec;

        /// <summary>"Tweet after 1sec.."</summary>
        public string Tweet_Step3_Before1Sec;

        /// <summary>"Posting the tweet..."</summary>
        public string Tweet_Step4_Posting;

        /// <summary>"Tweeted!"</summary>
        public string Tweet_Step5_Complete;

        /// <summary>"Tweeted"</summary>
        public string Tweeted;

        /// <summary>"Up"</summary>
        public string Up;

        /// <summary>"Yes"</summary>
        public string Yes;
    }
}
